# Generated by Django 5.0.6 on 2024-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(auto_created=2)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
