# Generated by Django 5.0.6 on 2024-06-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediCare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
